apiVersion: v2
name: radix-ingress-default-backend
icon: https://radix.equinor.com/images/logos/logo.svg
description: A ingress-nginx default backend for Radix
version: 1.2.0
appVersion: 1.2.0
kubeVersion: '>=1.24.0'
keywords:
  - radix
home: radix.equinor.com
sources:
  - https://github.com/equinor/radix-ingress-default-backend
maintainers:
  - name: Omnia Radix
    email: Radix@StatoilSRM.onmicrosoft.com
